name: Build and Package DMG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        id: set-up-homebrew

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build the application
        run: |
          source venv/bin/activate
          ./bundle.sh

      - name: Upload DMG file
        uses: actions/upload-artifact@v2
        with:
          name: ImageProcessor-dmg
          path: dist/ImageProcessor.dmg

      - name: Create version file
        run: echo ${{ github.sha }} > version.txt

      - name: Upload DMG to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/ImageProcessor.dmg
          remote: /var/www/matrunchyk.com/web/ImageProcessor/ImageProcessor.dmg
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          verbose: true
	  rmRemote: true

      - name: Upload version file to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: version.txt
          remote: /var/www/matrunchyk.com/web/ImageProcessor/version.txt
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
	  verbose: true
	  rmRemote: true


